### PR TITLE
T/38 Make remove on image abortion permanent

### LINKED ISSUE #38: Fix integration with undo.
There are two main issues with upload and undo:

- `uploadStatus` attribute is changed when undoing/redoing which is incorrect, because it should be only changed on upload changes. Also, the upload is already aborted but undo/redo may change the `uploadStatus` to incorrect value.

- after refactoring `RemoveOperation`, `History`, OT and undo, removing of "image placeholder" can be undone, which is incorrect because that image upload is aborted when "image placeholder" is removed.

The solutions are:
1. `uploadStatus` changes has to be done in separate, transparent batches (or, maybe even totally removed from model) so undo does not "see" them.
2. removing of "image placeholder" has to be done using `isPermanent` flag, in separate batch (preferably a transparent batch, but normal batch should also work as permanent remove operation is reversed to `NoOperation` anyway).

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: When image upload is aborted, now the "image placeholder" element is permanently removed so it is not reinserted on undo. Closes #38.

---

### Additional information

Additionally, `uploadStatus` attribute does not change on undo/redo, although this is less important, as image element is in graveyard anyway. Still, this means that there are less deltas created and applied so there are less objects in `engine.model.History` and it is easier to debug.

### CODE REVIEW

**Comment by scofalik** [comment]
This depends on
https://github.com/ckeditor/ckeditor5-engine/pull/977
https://github.com/ckeditor/ckeditor5-undo/pull/63

File: tests/imageuploadengine.js [hunk 1]
```diff
@@ -234,4 +235,48 @@ describe( 'ImageUploadEngine', () => {
 		expect( loader.status ).to.equal( 'aborted' );
 		sinon.assert.calledOnce( abortSpy );
 	} );
+
+	it( 'image should be permanently removed if it is removed by user during upload', done => {
```
Comment (scofalik) [inline tests/imageuploadengine.js]: Honestly, I hate this test and how you need to use three consecutive `document#event:changesDone` to test something "just after the image placeholder is removed".

It's hard to test it because the image is removed in a `Promise`'s catch callback and the `Promise` is not returned anywhere. This test (and a test above that was already there) are very prone to fail in future because of theoretically unrelated changes.
